# Trailing commas make for clearer diffs because the last line won't appear
# to have been changed, as it would if it lacked a comma and had one added.
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    # Using `[]` for string arrays instead of `()`, since normal arrays are
    # indicated with `[]` not `()`.
    '%w': '[]'
    '%W': '[]'

Style/AsciiComments:
  AllowedChars:
    - '∆'

Style/AndOr:
  # `and` and `or` banned only in conditionals (conditionals), or completely (always).
  EnforcedStyle: 'always'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Style/IfUnlessModifier:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

Metrics/LineLength:
  Max: 140
  Exclude:
    - 'config/routes.rb'

Metrics/BlockLength:
  Max: 25

Layout/IndentFirstArrayElement:
  EnforcedStyle: 'consistent'
